# -*- coding: utf-8 -*-
"""Ex1: Escrevendo " Ola mundo ".py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11D_MrzJ3mQBxUVC895QsFA9uz-zj0RSq
"""

print('Olá, Mundo!')