# -*- coding: utf-8 -*-
"""Ex005: Antecessor e Sucessor

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11D_MrzJ3mQBxUVC895QsFA9uz-zj0RSq
"""

n = int(input('Digite um número inteiro: '))
ante = n - 1
suce = n + 1

print(f'\nO Antecessor de {n} é {ante} e seu Sucessor é {suce}!')