# -*- coding: utf-8 -*-
"""Ex3:

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11D_MrzJ3mQBxUVC895QsFA9uz-zj0RSq
"""

nome = input('Qual é o seu nome ? ')

print(f'É um prazer te conhecer, {nome}!')