# -*- coding: utf-8 -*-
"""Ex3: soma de 2 numeros

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11D_MrzJ3mQBxUVC895QsFA9uz-zj0RSq
"""

valor_1 = float(input('Digite um valor: '))
valor_2 = float(input('Digite outro valor: '))
soma = valor_1 + valor_2

print(f'A soma de {valor_1} e {valor_2} é igual: {soma}!')