# -*- coding: utf-8 -*-
"""Ex4: Dissecando uma variavel

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11D_MrzJ3mQBxUVC895QsFA9uz-zj0RSq
"""

algo = input('Digite algo: ')

print(type(algo))
print(f'Só tem espaços? {algo.isspace()}')
print(f'É um número? {algo.isnumeric()}')
print(f'É alfabético? {algo.isalpha()}')
print(f'É alfanuméco? {algo.isalnum()}')
print(f'Está em maiúsculas? {algo.isupper()}')
print(f'Está em minúsculas? {algo.islower()}')
print(f'Está capitalizada? {algo.istitle()}')